### ISSUE TITLE
Strange db import issue?

### ISSUE THREAD

**Issue by Inexpli** [Inexpli/Flask-signup-and-login-WebApplication#1]
Traceback (most recent call last):
  File "d:/GitHub Repositories/Flask-WebApp/main.py", line 1, in <module>
    from website import create_app
  File "d:\GitHub Repositories\Flask-WebApp\website\__init__.py", line 5, in <module>
    from .models import User
  File "d:\GitHub Repositories\Flask-WebApp\website\models.py", line 1, in <module>
    from . import db
ImportError: cannot import name 'db'

![image](https://user-images.githubusercontent.com/61479966/111514538-21dafd80-8752-11eb-81ad-3e3ca60ec9a2.png)
![image](https://user-images.githubusercontent.com/61479966/111514615-328b7380-8752-11eb-9588-04fb07580cc9.png)

**Comment by gavwellis** [comment]
Hey!

Try using 'from website import db' instead.

Gav

**Comment by Inexpli** [comment]
> Hey!
> 
> Try using 'from website import db' instead.
> 
> Gav

Same error
![image](https://user-images.githubusercontent.com/61479966/111557750-90897c80-878d-11eb-904e-f5745011a7bd.png)
